export const initialState = {
  blogs: [
    {
      id: "1",
      title: "React patterns",
      author: "Jhankar Mahbub",
      blogImg:
        "https://images.unsplash.com/photo-1496128858413-b36217c2ce36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80",
      authorImg: "https://unsplash.com/photos/v2aKnjMbP_k",
      category: "JavaScript",
      date: "11 Jul, 2022",
      readTime: "5 min read",
    },
    {
      id: "2",
      title: "JavaScript Debugging with Chrome DevTools",
      author: "Anisul Islam",
      blogImg: "https://unsplash.com/photos/SYTO3xs06fU",
      authorImg: "https://unsplash.com/photos/6GgCyNnF6Zs",
      category: "React",
      date: "05 Feb, 2022",
      readTime: "8 min read",
    },
    {
      id: "3",
      title: "How to use search engine optimization to drive sales",
      author: "Saidur Rahman Setu",
      blogImg: "https://unsplash.com/photos/BfrQnKBulYQ",
      authorImg: "https://unsplash.com/photos/4_QFycgpC4c",
      category: "NodeJS",
      date: "06 Jan, 2022",
      readTime: "10 min read",
    },
    {
      id: "4",
      title: "Boost your conversion rate",
      author: "HM Nayem",
      blogImg: "https://unsplash.com/photos/npxXWgQ33ZQ",
      authorImg: "https://unsplash.com/photos/SPcFpXIME6M",
      category: "ExpressJS",
      date: "17 Apr, 2022",
      readTime: "6 min read",
    },
    {
      id: "5",
      title: "How to use search engine optimization to drive sales",
      author: "Akash Ahmed",
      blogImg: "https://unsplash.com/photos/m_HRfLhgABo",
      authorImg: "https://unsplash.com/photos/3GUn7wUs52I",
      category: "Tailwind CSS",
      date: "23 Mar, 2022",
      readTime: "4 min read",
    },
    {
      id: "6",
      title: "JavaScript Closure",
      author: "Sumit Saha",
      blogImg: "https://unsplash.com/photos/SyvsTmuuZyM",
      authorImg: "https://unsplash.com/photos/DItYlc26zVI",
      category: "Redux",
      date: "10 Sep, 2021",
      readTime: "7 min read",
    },
    {
      id: "7",
      title: "JavaScript Hoisting",
      author: "HM Nayem",
      blogImg: "https://unsplash.com/photos/FCHlYvR5gJI",
      authorImg: "https://unsplash.com/photos/SPcFpXIME6M",
      category: "Tailwind CSS",
      date: "10 Sep, 2021",
      readTime: "7 min read",
    },
    {
      id: "8",
      title: "Learn JavaScript in 10 minutes",
      author: "Saidur Rahman Setu",
      blogImg: "https://unsplash.com/photos/qAjJk-un3BI",
      authorImg: "https://unsplash.com/photos/4_QFycgpC4c",
      category: "MongoDB",
      date: "10 Sep, 2021",
      readTime: "7 min read",
    },
    {
      id: "9",
      title: "Easily create a responsive website",
      author: "Jhankar Mahbub",
      blogImg: "https://unsplash.com/photos/gcsNOsPEXfs",
      authorImg: "https://unsplash.com/photos/v2aKnjMbP_k",
      category: "ExpressJS",
      date: "10 Sep, 2021",
      readTime: "7 min read",
    },
    {
      id: "10",
      title: "Join the React community",
      author: "Sumit Saha",
      blogImg: "https://unsplash.com/photos/5fNmWej4tAA",
      authorImg: "https://unsplash.com/photos/DItYlc26zVI",
      category: "Redux",
      date: "10 Sep, 2021",
      readTime: "7 min read",
    },
    {
      id: "11",
      title: "Get started with React",
      author: "Anisul Islam",
      blogImg: "https://unsplash.com/photos/hGV2TfOh0ns",
      authorImg: "https://unsplash.com/photos/6GgCyNnF6Zs",
      category: "NodeJS",
      date: "10 Sep, 2021",
      readTime: "7 min read",
    },
    {
      id: "12",
      title: "Start your own React project",
      author: "Akash Ahmed",
      blogImg: "https://unsplash.com/photos/jJT2r2n7lYA",
      authorImg: "https://unsplash.com/photos/3GUn7wUs52I",
      category: "React",
      date: "10 Sep, 2021",
      readTime: "7 min read",
    },
    {
      id: "13",
      title: "Code your first React component",
      author: "Sumit Saha",
      blogImg: "https://unsplash.com/photos/WFSap6CIXuw",
      authorImg: "https://unsplash.com/photos/DItYlc26zVI",
      category: "JavaScript",
      date: "10 Sep, 2021",
      readTime: "7 min read",
    },
  ],
};