export const CATEGORY_FILTER = "FILTER/CATEGORY_FILTER";
export const SEARCH_FILTER = "FILTER/SEARCH_FILTER";
export const AUTHOR_FILTER = "FILTER/AUTHOR_FILTER";
export const REMOVE_FILTER = "FILTER/REMOVE_FILTER";
export const REMOVE_SEARCH_FILTER = "FILTER/REMOVE_SEARCH_FILTER";
export const REMOVE_CATEGORY_FILTER = "FILTER/REMOVE_CATEGORY_FILTER";
export const REMOVE_AUTHOR_FILTER = "FILTER/REMOVE_AUTHOR_FILTER";

